from enum import Enum


class REJECTION_REASON(Enum):
    NOT_ALLOWED_BACKGROUND = "NOT_ALLOWED_BACKGROUND"
    COVERED_FACE = "COVERED_FACE"
    NO_PERSON_RECOGNIZED = "NO_PERSON_RECOGNIZED"
    OTHER_REASON = "OTHER_REASON"
    NONE = "NONE"