from enum import Enum


class STUDENT_STATE(Enum):
    APPROVED = "APPROVED"
    NO_SELFIE = "NO_SELFIE"
    SELFIE_IN_REVIEW  = "SELFIE_IN_REVIEW"
    SELFIE_REJECTED  = "SELFIE_REJECTED"
    SELFIE_PENDING_REVIEW = "SELFIE_PENDING_REVIEW"
